name: 🧘 Keep Workflows Active

on:
  schedule:
    # Run on the 1st day of every month at 3:05 AM
    - cron: '5 3 1 * *'
  workflow_dispatch:

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update activity timestamp
        run: |
          mkdir -p .github/activity
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > .github/activity/timestamp

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore(activity): Update timestamp to keep workflows active"
          branch: repo-keepalive
          delete-branch: true
          title: "chore(activity): Keep workflows active"
          body: "Automated PR to update the activity timestamp and keep workflows active."
          author: "buildplan <hello@buildplan.org>"
          committer: "buildplan <hello@buildplan.org>"

      - name: Merge Pull Request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh pr merge "${{ steps.cpr.outputs.pull-request-number }}" --admin --squash --delete-branch || \
          gh pr merge "${{ steps.cpr.outputs.pull-request-number }}" --auto --squash --delete-branch
